twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        navBarMenusRepository: "@App\\Repository\\NavbarMenuRepository"
        categorySkillRepository: "@App\\Repository\\CategorySkillRepository"
